name: foundry-ci

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: default

jobs:
  check:
    name: Foundry Project
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Show Foundry config
        run: forge config

      - name: Clean previous builds
        run: forge clean

      - name: Run Forge build
        run: |
          forge --version
          forge build

      - name: Run Forge tests
        run: forge test -vvv
